services:
  wwebjs:
    build: .
    container_name: wwebjs-app
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./app/.wwebjs_auth:/app/.wwebjs_auth
      - ./app/.wwebjs_cache:/app/.wwebjs_cache
      - ./app/sess:/app/sess
    environment:
      - NODE_ENV=production
      - WS_ROOT=ws://193.46.198.228:8082
      - API_ROOT=https://apiwa.sefil.com.ec/public/api
      - PUBLIC_PATH=https://apiwa.sefil.com.ec/public/
    shm_size: '2gb'
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 2G